### PR TITLE
v0.4.3

### LINKED ISSUE #64: Add aliases autographr/autographs/autographt (with a t instead of a d) or even graphr/graphs/grapht

### LINKED ISSUE #65: `autographs()` and `autographt()` fail to properly plot network diffusion
It appears that `autographs()` and `autographt()` is not currently plotting diffusion through networks properly. For instance:

`autographs(play_diffusion(ison_adolescents))`
`autographs(play_diffusion(ison_adolescents, seeds = 4))`
`autographs(play_diffusion(ison_adolescents, latency = 0.5))`
`autographt(play_diffusion(ison_adolescents))`

All display the same network incorrectly (as if no nodes were infected) but both `play_diffusions()` and `autographr()` appear to be working fine...

`play_diffusion(ison_adolescents)`
`autographr(play_diffusion(ison_adolescents))`

### PR DESCRIPTION
**Pull request by henriquesposito**
# Description

Fixes issues with CRAN submission.

## Mapping

- Fixed issues with `autographr()` examples that were taking too long to run
- Separated documentation for `autographr()`, `autographs()`, and `autographd()` functions
- Closed #64 by adding aliases for `autographr()`, `autographs()`, and `autographd()` functions
- Closed #65 by fixing bugs with how `node_is_infected()`, `node_is_recovery()`, `node_is_latent()` work for network lists

# Checklist:

- PR form
  - [x] Description above itemizes changes under subtitles, e.g. "## Data""
  - [x] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [x] Package builds on my OS without issues
- PR checks all pass for latest commit
  - [ ] CodeFactor check: Package improves or maintains good style
  - [x] Package builds on Mac
  - [x] Package builds on Windows
  - [x] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
- Documentation
  - [x] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [x] Longer functions are commented inline or broken down into helper functions so that it is easier to debug in the future
  - [x] PR description above and the NEWS.md file are aligned
  - [x] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

### CODE REVIEW

File: R/map_autographr.R [hunk 1]
```diff
@@ -76,29 +76,18 @@ NULL
...
-#' #ison_adolescents %>%
-#' #   mutate(year = rep(c(1985, 1990, 1995, 2000), times = 2)) %>%
-#' #   autographr(layout = "lineage", rank = "year")
-#' #ison_adolescents %>%
-#' #   mutate(cut = node_is_cutpoint(ison_adolescents)) %>%
-#' #autographr(node_color = "cut", node_shape = "cut")
+#' ison_adolescents |>
+#'   mutate(color = rep(c("extrovert", "introvert"), times = 4),
+#'          size = ifelse(node_is_cutpoint(ison_adolescents), 6, 3)) |>
+#'          mutate_ties(ecolor = rep(c("friends", "aquaintances"), times = 5)) |>
```
Comment (jhollway) [inline R/map_autographr.R:82]: Align `mutate_ties(` with the function line above?

**Review by jhollway — APPROVED** [review]
